### ISSUE TITLE
Can't load the country flag icons. The flags appears as strings in the UI.

### ISSUE THREAD

**Issue by nazmulrony** [AntonioErdeljac/next13-airbnb-clone#43]
I had a look at the raw country data. Each country has a flag property that is a string. I don't know how you are showing the flags like flag icons.

![image](https://github.com/AntonioErdeljac/next13-airbnb-clone/assets/98468670/7dbd9c76-e9a5-48aa-9391-cf7045fd8a56)

**Comment by Yergeni** [comment]
Hi @nazmulrony 

I noticed the same issue and it looks like this is related to the platform and not an issue with the code. Please take a look at this [discussion](https://stackoverflow.com/questions/54519758/flag-emojis-not-rendering/54663926) for more details.

I was trying to solve it by replacing the `span` that renders the flag using this code but I didn't like the idea of loading the png files as the user scrolls. For now, I create a TODO to solve it later after I finish the course.

```
<Image
   src={flagCdnUrl + option.value.toLowerCase() + ".svg"}
   alt={option.value}
   className="h-auto w-[16px] aspect-auto"
   width={16}
   height={16}
/>
```

flagCdnURL is `const flagCdnUrl = "https://flagcdn.com/"`;

**Comment by nazmulrony** [comment]
Thanks, @Yergeni 
This code worked for me. 
But, I tried using option.flag.toLowerCase(). Don't know why it doesn't work.

**Comment by Yergeni** [comment]
@nazmulrony 

For the code I sent above to work you need to pass the `value` which is the **cca2 ISO code** property of the options instead of the `flag` property. If you take a look at the [word-countries](https://www.npmjs.com/package/world-countries) package being used and then compare it with the service that I used [flagcdn](https://flagpedia.net/download/api) to provide the icon instead of the emoji code. For example:

If you want to render the AT flag **svg** icon instead of the emoji. The `word-countries` package provides this object:
```js
{
   ...
   "cca2": "AT", // this is the value needed for the flagcdn to provide the SVG icon
   "flag": "\ud83c\udde6\ud83c\uddf9" // this is the flag emoji code.
   ...
}
```
and this is the object we are constructing from the `word-countries` package:

```ts
const formattedCountries: CountryValue[] = countries.map((country) => ({
	value: country.cca2, // notice here that value is the needed ISO code in lower case for the flagcdn to provide the right icon
	label: country.name.common,
	flag: country.flag,
	latlng: country.latlng,
	region: country.region,
}));
```

Finally, the `Image` element in the **formatOptionLabel** prop of the country select component should have this source:

`src={flagCdnUrl + option.value.toLowerCase() + ".svg"}`

**Comment by Dawitlior** [comment]
basically i don't think you did something wrong, it's a common issue in windows. If you want to see emojis you can use firefox.

**Comment by saeid4x** [comment]
for see flag icon, you should install "country flag fixer" chrome Extension
